# Generated by Django 5.1 on 2025-10-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
