# Generated by Django 5.1 on 2025-10-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_car_owner_alter_car_year_of_manufacture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('logged_expiry_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='cars.car')),
            ],
            options={
                'db_table': 'insurance_policy',
                'indexes': [models.Index(fields=['car', 'start_date', 'end_date'], name='idx_policy_car_dates')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='chk_policy_end_after_start')],
            },
        ),
    ]
