# Generated by Django 5.1 on 2025-10-21 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceExpiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_log', to='policies.insurancepolicy')),
            ],
            options={
                'db_table': 'insurance_expiry_log',
                'indexes': [models.Index(fields=['policy', 'logged_at'], name='idx_expirylog_policy_loggedat')],
                'constraints': [models.UniqueConstraint(fields=('policy',), name='uniq_expirylog_policy')],
            },
        ),
    ]
